# Pandas

Pandas is the most popular python library that is used for data analysis.
We can analyze data in pandas with:
1.Series
2.DataFrames

Series:  Series is one dimensional(1-D) array defined in pandas that can be used to store any data
Data Frames : DataFrames is two-dimensional(2-D) data structure defined in pandas which consists of rows and columns.

In [1]:
import pandas as pd
# Program to Create series with scalar values  
Data =[1, 3, 4, 5, 6, 2, 9]  # Numeric data 
  
# Creating series with default index values 
s = pd.Series(Data)     
s 
# predefined index values

0    1
1    3
2    4
3    5
4    6
5    2
6    9
dtype: int64

In [2]:
#Creating With DataFrames
s1=pd.DataFrame(Data)
s1

   0
0  1
1  3
2  4
3  5
4  6
5  2
6  9

##### File Read and Write Operation

In [3]:
import pandas as pd
import numpy as np

data=pd.read_csv('C://Users//arjun//Desktop//Datasets//titanic.csv')
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

#### Read a tsv into a DataFrame

In [4]:
tdata=pd.read_table('C://Users//arjun//Desktop//Datasets//test.tsv')
tdata

        Name  PayRate  HoursWorked
0      Arjun       10         12.0
1        Ram        8          8.0
2  Harsha  5        6          NaN
3     Bhuvan       12         10.0

##### Read CSV file

In [5]:
data=pd.read_csv('C://Users//arjun//Desktop//Datasets//ex1.csv')
data.head()

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [6]:
data=pd.read_csv('C://Users//arjun//Desktop//Datasets//ex2.csv',header=None)
data.head()

   0   1   2   3       4
0  4   9   8   5    Hi..
1  1   2   3   4   hello
2  5   6   7   8   world
3  9  10  11  12  Python

In [7]:
#Assigning customised columnsnames
data = pd.read_csv('C://Users//arjun//Desktop//Datasets//ex2.csv',names=['sub1','sub2','sub3','sub4'])
data

   sub1  sub2  sub3    sub4
4     9     8     5    Hi..
1     2     3     4   hello
5     6     7     8   world
9    10    11    12  Python

In [8]:
#using index columns
data = pd.read_csv('C://Users//arjun//Desktop//Datasets//csv_mindex.csv')
data

  key1 key2  value1  value2
0  one    a       1       2
1  one    b       3       4
2  one    c       5       6
3  one    d       7       8
4  two    a       9      10
5  two    b      11      12
6  two    c      13      14
7  two    d      15      16

In [9]:
data = pd.read_csv('C://Users//arjun//Desktop//Datasets//csv_mindex.csv',index_col=['key1','key2'])
data

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [10]:
#Skip rows 
data = pd.read_csv('C://Users//arjun//Desktop//Datasets//csv_mindex.csv',skiprows=[2,4,6])
data

  key1 key2  value1  value2
0  one    a       1       2
1  one    c       5       6
2  two    a       9      10
3  two    c      13      14
4  two    d      15      16

In [11]:
#Checking missing values
#Method 1:
data = pd.read_csv('C://Users//arjun//Desktop//Datasets//ex5.csv')
data
pd.isnull(data)

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False
3      False  False  False  False  False    False

In [12]:
#Method 2:
data.isnull().sum()

something    0
a            0
b            0
c            1
d            0
message      1
dtype: int64

##### Read Excel file

In [13]:
edata = pd.read_excel('C://Users//arjun//Desktop//Datasets//Online Retail.xlsx',sheet_name='Online_Retail')
edata.head()

,InvoiceNo,StockCode,lower,Description,CustomerID
0,536365,85123A,white hanging heart t-light holder,WHITE HANGING HEART T-LIGHT HOLDER,17850
1,536365,71053,white metal lantern,WHITE METAL LANTERN,17850
2,536365,84406B,cream cupid hearts coat hanger,CREAM CUPID HEARTS COAT HANGER,17850
3,536365,84029G,knitted union flag hot water bottle,KNITTED UNION FLAG HOT WATER BOTTLE,17850
4,536365,84029E,red woolly hottie white heart.,RED WOOLLY HOTTIE WHITE HEART.,17850

##### Read data from the specified url

In [14]:
url = "http://www.basketball-reference.com/leagues/NBA_2015_totals.html"
udata = pd.read_html(url)
udata[0].ix[:, 0:10].head(5)      # Check 5 rows (10 columns only) #udata[0] is the url index location

C:\Users\arjun\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  This is separate from the ipykernel package so we can avoid doing imports until

  Rk         Player Pos Age   Tm   G  GS    MP   FG  FGA
0  1     Quincy Acy  PF  24  NYK  68  22  1287  152  331
1  2   Jordan Adams  SG  20  MEM  30   0   248   35   86
2  3   Steven Adams   C  21  OKC  70  67  1771  217  399
3  4    Jeff Adrien  PF  28  MIN  17   0   215   19   44
4  5  Arron Afflalo  SG  29  TOT  78  72  2502  375  884

In [15]:
udata[0].head()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,...,.784,79,222,301,68,27,22,60,147,398
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,...,.609,9,19,28,16,16,7,14,24,94
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,...,.502,199,324,523,66,38,86,99,222,537
3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,44,...,.579,23,54,77,15,4,9,9,30,60
4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,884,...,.843,27,220,247,129,41,7,116,167,1035

In [16]:
titanic_data= pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
                           sep='\t')  
titanic_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [17]:
#to select specific columns
titanic_data[["Name","Pclass"]].head()

                                                Name  Pclass
0                            Braund, Mr. Owen Harris       3
1  Cumings, Mrs. John Bradley (Florence Briggs Th...       1
2                             Heikkinen, Miss. Laina       3
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1
4                           Allen, Mr. William Henry       3

In [18]:
#check dataset datatypes
#Method 1:
titanic_data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [19]:
#Method 2:
titanic_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
PassengerId    156 non-null int64
Survived       156 non-null int64
Pclass         156 non-null int64
Name           156 non-null object
Sex            156 non-null object
Age            126 non-null float64
SibSp          156 non-null int64
Parch          156 non-null int64
Ticket         156 non-null object
Fare           156 non-null float64
Cabin          31 non-null object
Embarked       155 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 14.7+ KB

In [20]:
data = pd.read_csv('C://Users//arjun//Desktop//Datasets//ex6.csv',nrows=5)  #Print first 5 rows only
data

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [21]:
chunk=pd.read_csv('C://Users//arjun//Desktop//Datasets//ex6.csv',chunksize=10000)
chunk       #chunksize is used for read the file data wit the mentioned size only.  10000= 10KB

In [22]:
data = pd.read_csv('C://Users//arjun//Desktop//Datasets//out.csv')
data   #In below dataframe NAN is missing values

  something    a   b     c   d message
0       one  1.0   2   3.0   4     NaN
1       two  5.0   6   NaN   8   world
2     three  NaN  10  11.0  12     foo

In [23]:
data = pd.read_csv('C://Users//arjun//Desktop//Datasets//out.csv',sep='@')
data   #In below dataframe @ is not availabe so it is not separated, by default is separated by comma

  something,a,b,c,d,message
0              one,1,2,3,4,
1          two,5,6,,8,world
2       three,,10,11,12,foo

#### To Save a file

In [24]:
import sys 
data.to_csv('C://Users//arjun//Desktop//Datasets//out1.csv',sep='@')
data1=pd.read_csv('C://Users//arjun//Desktop//Datasets//out1.csv')
data1

  @something    a   b     c   d message
0      0@one  1.0   2   3.0   4     NaN
1      1@two  5.0   6   NaN   8   world
2    2@three  NaN  10  11.0  12     foo

In [25]:
data2=pd.read_csv('C://Users//arjun//Desktop//Datasets//out1.csv')
data2

  @something    a   b     c   d message
0      0@one  1.0   2   3.0   4     NaN
1      1@two  5.0   6   NaN   8   world
2    2@three  NaN  10  11.0  12     foo

In [26]:
data3=pd.read_csv('C://Users//arjun//Desktop//Datasets//out1.csv',usecols=['a', 'b', 'c'])
data3.head()

     a   b     c
0  1.0   2   3.0
1  5.0   6   NaN
2  NaN  10  11.0

In [27]:
import numpy as np
dates = pd.date_range('1/1/2000', periods=7)
ts = pd.Series(np.arange(7), index=dates)
ts
time=ts.to_csv('C://Users//arjun//Desktop//Datasets//tseries.csv')

In [28]:
pd.DataFrame(ts)

            0
2000-01-01  0
2000-01-02  1
2000-01-03  2
2000-01-04  3
2000-01-05  4
2000-01-06  5
2000-01-07  6

##### Working with Delimited Formats

In [29]:
import csv
f = open('C://Users//arjun//Desktop//Datasets//ex7.csv')
reader = csv.reader(f)
reader

In [30]:
#to see the data of csv file use below method
for line in reader:
    print(line)

['a', 'b', 'c']
['1', '2', '3']
['4', '5', '6']
['7', '8', '9']

In [31]:
with open('C://Users//arjun//Desktop//Datasets//ex7.csv') as f:
    lines = list(csv.reader(f))
lines

[['a', 'b', 'c'], ['1', '2', '3'], ['4', '5', '6'], ['7', '8', '9']]

In [32]:
lines[0]

['a', 'b', 'c']

In [33]:
lines[2]

['4', '5', '6']

###### Python zip() Function

Python zip() Function
The zip() function returns a zip object, which is an iterator of tuples where the first item in each passed iterator is paired together, and then the second item in each passed iterator are paired together etc.

In [34]:
header,values = lines[0],lines[1:]

In [35]:
header

['a', 'b', 'c']

In [36]:
values

[['1', '2', '3'], ['4', '5', '6'], ['7', '8', '9']]

In [37]:
data_dict={h: v for h, v in zip(header,zip(*values))}
data_dict

{'a': ('1', '4', '7'), 'b': ('2', '5', '8'), 'c': ('3', '6', '9')}

#### JSON Data (JavaScript Object Notation)

In [38]:
obj = """
{"name": "Wes",
 "places_lived": ["United States", "Spain", "Germany"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]},
              {"name": "Katie", "age": 38,
               "pets": ["Sixes", "Stache", "Cisco"]}]
}
"""

In [39]:
import json
result = json.loads(obj)
result

{'name': 'Wes',
 'places_lived': ['United States', 'Spain', 'Germany'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 30, 'pets': ['Zeus', 'Zuko']},
  {'name': 'Katie', 'age': 38, 'pets': ['Sixes', 'Stache', 'Cisco']}]}

In [40]:
asjson = json.dumps(result)
asjson

'{"name": "Wes", "places_lived": ["United States", "Spain", "Germany"], "pet": null, "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]}, {"name": "Katie", "age": 38, "pets": ["Sixes", "Stache", "Cisco"]}]}'

In [41]:
siblings = pd.DataFrame(result['siblings'],columns=['name', 'age', 'pets'])
siblings

    name  age                    pets
0  Scott   30            [Zeus, Zuko]
1  Katie   38  [Sixes, Stache, Cisco]

###### To Read Json file

In [42]:
data=pd.read_json('C://Users//arjun//Desktop//Datasets//example.json')
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

###### To Save Json file

In [43]:
records=data.to_json('C://Users//arjun//Desktop//Datasets//records.json')

In [44]:
print(data.to_json())
print(data.to_json(orient='records'))

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}
[{"a":1,"b":2,"c":3},{"a":4,"b":5,"c":6},{"a":7,"b":8,"c":9}]

###### Read data with html file

In [45]:
data=pd.read_html('C://Users//arjun//Desktop//Datasets//fdic_failed_bank_list.html')
print(len(data))
data_table=data[0]
data_table.head()

1

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016"
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016"
2,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,"May 6, 2016","September 6, 2016"
3,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,"April 29, 2016","September 6, 2016"
4,North Milwaukee State Bank,Milwaukee,WI,20364,First-Citizens Bank & Trust Company,"March 11, 2016","June 16, 2016"

In [46]:
close_timestamps = pd.to_datetime(data_table['Closing Date'])
close_timestamps.dt.year.value_counts()

2010    157
2009    140
2011     92
2012     51
2008     25
2013     24
2014     18
2002     11
2015      8
2016      5
2004      4
2001      4
2007      3
2003      3
2000      2
Name: Closing Date, dtype: int64

###### Binary Data Formats

In [47]:
frame=pd.read_csv('C://Users//arjun//Desktop//Datasets//ex6.csv')
frame.head()
frame.to_pickle('C://Users//arjun//Desktop//Datasets//frame_pickle.csv') #pickle is generay u

pickle — Python object serialization. ... “Pickling” is the process whereby a Python object hierarchy is converted into a byte stream, and “unpickling” is the inverse operation, whereby a byte stream is converted back into an object hierarchy.

In [48]:
pd.read_pickle('C://Users//arjun//Desktop//Datasets//frame_pickle.csv').head()

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

##### Using HDF5 Format

In [49]:
frame = pd.DataFrame({'a': np.random.randn(100)})
store = pd.HDFStore('mydata.h5')
store['obj1'] = frame
store['obj1_col'] = frame['a']
store

<class 'pandas.io.pytables.HDFStore'>
File path: mydata.h5

In [50]:
store['obj1'].head()

          a
0  0.878235
1 -0.708524
2 -0.997467
3  0.322499
4  0.589680

In [51]:
store.put('obj2', frame, format='table')
store.select('obj2', where=['index >= 10 and index <= 15'])
store.close()

In [52]:
frame.to_hdf('mydata.h5', 'obj3', format='table')
pd.read_hdf('mydata.h5', 'obj3', where=['index < 5'])

          a
0  0.878235
1 -0.708524
2 -0.997467
3  0.322499
4  0.589680

###### Reading Data with Web APIs

In [53]:
import requests
url='https://api.github.com/repos/pandas-dev/pandas/issues'
resp=requests.get(url)
resp

In [54]:
data=resp.json()
data

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/30708',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/30708/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/30708/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/30708/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/30708',
  'id': 545405870,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0MzU5MjkzMTky',
  'number': 30708,
  'title': 'CI: Test case for wrong placed space',
  'user': {'login': 'MomIsBestFriend',
   'id': 50263213,
   'node_id': 'MDQ6VXNlcjUwMjYzMjEz',
   'avatar_url': 'https://avatars0.githubusercontent.com/u/50263213?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/MomIsBestFriend',
   'html_url': 'https://github.com/MomIsBestFriend',
   'followers_url': 'https://api.github.com/users/MomIsBestFriend/followers',
   'following_url': 'https://api.github.com/users/MomIsBestFriend/following{/other_user}',
   'gists_url': 'https://api.github.com/users/MomIsBestFriend/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/MomIsBestFriend/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/MomIsBestFriend/subscriptions',
   'organizations_url': 'https://api.github.com/users/MomIsBestFriend/orgs',
   'repos_url': 'https://api.github.com/users/MomIsBestFriend/repos',
   'events_url': 'https://api.github.com/users/MomIsBestFriend/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/MomIsBestFriend/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 48070600,
    'node_id': 'MDU6TGFiZWw0ODA3MDYwMA==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/CI',
    'name': 'CI',
    'color': 'a2bca7',
    'default': False,
    'description': None},
   {'id': 106935113,
    'node_id': 'MDU6TGFiZWwxMDY5MzUxMTM=',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Style',
    'name': 'Style',
    'color': 'eb6420',
    'default': False,
    'description': 'Code style, linting, code_checks'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2020-01-05T11:36:22Z',
  'updated_at': '2020-01-05T13:26:10Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/30708',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/30708',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/30708.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/30708.patch'},
  'body': '- [ ] closes #xxxx\r\n- [ ] tests added / passed\r\n- [x] passes `black pandas`\r\n- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`\r\n- [ ] whatsnew entry\r\n\r\nTest case for:\r\n```python\r\nfoo = (\r\n            "bar"\r\n            " baz"\r\n)\r\n```'},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/30707',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/30707/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/30707/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/30707/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/30707',
  'id': 545402893,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0MzU5MjkxMDY3',
  'number': 30707,
  'title': 'STY: Spaces over concat strings - batch 1',
  'user': {'login': 'MomIsBestFriend',
   'id': 50263213,
   'node_id': 'MDQ6VXNlcjUwMjYzMjEz',
   'avatar_url': 'https://avatars0.githubusercontent.com/u/50263213?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/MomIsBestFriend',
   'html_url': 'https://github.com/MomIsBestFriend',
   'followers_url': 'https://api.github.com/users/MomIsBestFriend/followers',
   'following_url': 'https://api.github.com/users/MomIsBestFriend/following{/other_user}',
   'gists_url': 'https://api.github.com/users/MomIsBestFriend/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/MomIsBestFriend/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/MomIsBestFriend/subscriptions',
   'organizations_url': 'https://api.github.com/users/MomIsBestFriend/orgs',
   'repos_url': 'https://api.github.com/users/MomIsBestFriend/repos',
   'events_url': 'https://api.github.com/users/MomIsBestFriend/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/MomIsBestFriend/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 106935113,
    'node_id': 'MDU6TGFiZWwxMDY5MzUxMTM=',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Style',
    'name': 'Style',
    'color': 'eb6420',
    'default': False,
    'description': 'Code style, linting, code_checks'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 1,
  'created_at': '2020-01-05T11:03:40Z',
  'updated_at': '2020-01-05T13:00:53Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/30707',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/30707',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/30707.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/30707.patch'},
  'body': '- [ ] closes #xxxx\r\n- [ ] tests added / passed\r\n- [x] passes `black pandas`\r\n- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`\r\n- [ ] whatsnew entry\r\n'},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/30706',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/30706/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/30706/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/30706/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/30706',
  'id': 545377775,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0MzU5Mjc1NDA5',
  'number': 30706,
  'title': "CLN: replacing '.format' with f-strings in various files",
  'user': {'login': 'AlfredoGJ',
   'id': 19152108,
   'node_id': 'MDQ6VXNlcjE5MTUyMTA4',
   'avatar_url': 'https://avatars3.githubusercontent.com/u/19152108?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/AlfredoGJ',
   'html_url': 'https://github.com/AlfredoGJ',
   'followers_url': 'https://api.github.com/users/AlfredoGJ/followers',
   'following_url': 'https://api.github.com/users/AlfredoGJ/following{/other_user}',
   'gists_url': 'https://api.github.com/users/AlfredoGJ/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/AlfredoGJ/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/AlfredoGJ/subscriptions',
   'organizations_url': 'https://api.github.com/users/AlfredoGJ/orgs',
   'repos_url': 'https://api.github.com/users/AlfredoGJ/repos',
   'events_url': 'https://api.github.com/users/AlfredoGJ/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/AlfredoGJ/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 106935113,
    'node_id': 'MDU6TGFiZWwxMDY5MzUxMTM=',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Style',
    'name': 'Style',
    'color': 'eb6420',
    'default': False,
    'description': 'Code style, linting, code_checks'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 1,
  'created_at': '2020-01-05T06:17:42Z',
  'updated_at': '2020-01-05T12:38:47Z',
  'closed_at': None,
  'author_association': 'NONE',
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/30706',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/30706',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/30706.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/30706.patch'},
  'body': '- [x]  contributes to #29547\r\n- [ ] tests added / passed\r\n- [X] passes `black pandas`\r\n- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`\r\n- [ ] whatsnew entry\r\n'},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/30705',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/30705/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/30705/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/30705/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/30705',
  'id': 545355244,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0MzU5MjYzMTE3',
  'number': 30705,
  'title': 'BUG: listlike comparisons for DTA and TDA',
  'user': {'login': 'jbrockmendel',
   'id': 8078968,
   'node_id': 'MDQ6VXNlcjgwNzg5Njg=',
   'avatar_url': 'https://avatars1.githubusercontent.com/u/8078968?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/jbrockmendel',
   'html_url': 'https://github.com/jbrockmendel',
   'followers_url': 'https://api.github.com/users/jbrockmendel/followers',
   'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}',
   'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions',
   'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs',
   'repos_url': 'https://api.github.com/users/jbrockmendel/repos',
   'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2020-01-05T01:43:31Z',
  'updated_at': '2020-01-05T01:43:31Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/30705',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/30705',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/30705.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/30705.patch'},
  'body': 'These will now match PeriodArray, and we can move to share the methods.'},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/30704',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/30704/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/30704/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/30704/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/30704',
  'id': 545351095,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0MzU5MjYwMTYx',
  'number': 30704,
  'title': 'REF: Share _fast_union between DTI/TDI',
  'user': {'login': 'jbrockmendel',
   'id': 8078968,
   'node_id': 'MDQ6VXNlcjgwNzg5Njg=',
   'avatar_url': 'https://avatars1.githubusercontent.com/u/8078968?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/jbrockmendel',
   'html_url': 'https://github.com/jbrockmendel',
   'followers_url': 'https://api.github.com/users/jbrockmendel/followers',
   'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}',
   'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions',
   'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs',
   'repos_url': 'https://api.github.com/users/jbrockmendel/repos',
   'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 1218227310,
    'node_id': 'MDU6TGFiZWwxMjE4MjI3MzEw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Index',
    'name': 'Index',
    'color': 'e99695',
    'default': False,
    'description': 'Related to the Index class or subclasses'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': {'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/16',
   'html_url': 'https://github.com/pandas-dev/pandas/milestone/16',
   'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/16/labels',
   'id': 174211,
   'node_id': 'MDk6TWlsZXN0b25lMTc0MjEx',
   'number': 16,
   'title': '1.0',
   'description': '',
   'creator': {'login': 'wesm',
    'id': 329591,
    'node_id': 'MDQ6VXNlcjMyOTU5MQ==',
    'avatar_url': 'https://avatars2.githubusercontent.com/u/329591?v=4',
    'gravatar_id': '',
    'url': 'https://api.github.com/users/wesm',
    'html_url': 'https://github.com/wesm',
    'followers_url': 'https://api.github.com/users/wesm/followers',
    'following_url': 'https://api.github.com/users/wesm/following{/other_user}',
    'gists_url': 'https://api.github.com/users/wesm/gists{/gist_id}',
    'starred_url': 'https://api.github.com/users/wesm/starred{/owner}{/repo}',
    'subscriptions_url': 'https://api.github.com/users/wesm/subscriptions',
    'organizations_url': 'https://api.github.com/users/wesm/orgs',
    'repos_url': 'https://api.github.com/users/wesm/repos',
    'events_url': 'https://api.github.com/users/wesm/events{/privacy}',
    'received_events_url': 'https://api.github.com/users/wesm/received_events',
    'type': 'User',
    'site_admin': False},
   'open_issues': 58,
   'closed_issues': 1908,
   'state': 'open',
   'created_at': '2012-09-13T02:13:00Z',
   'updated_at': '2020-01-05T00:57:38Z',
   'due_on': '2020-02-01T08:00:00Z',
   'closed_at': None},
  'comments': 0,
  'created_at': '2020-01-05T00:46:51Z',
  'updated_at': '2020-01-05T02:48:43Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/30704',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/30704',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/30704.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/30704.patch'},
  'body': ''},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/30703',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/30703/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/30703/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/30703/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/30703',
  'id': 545344645,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0MzU5MjU1ODQ1',
  'number': 30703,
  'title': 'Implement ExtensionIndex',
  'user': {'login': 'jbrockmendel',
   'id': 8078968,
   'node_id': 'MDQ6VXNlcjgwNzg5Njg=',
   'avatar_url': 'https://avatars1.githubusercontent.com/u/8078968?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/jbrockmendel',
   'html_url': 'https://github.com/jbrockmendel',
   'followers_url': 'https://api.github.com/users/jbrockmendel/followers',
   'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}',
   'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions',
   'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs',
   'repos_url': 'https://api.github.com/users/jbrockmendel/repos',
   'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 1465286368,
    'node_id': 'MDU6TGFiZWwxNDY1Mjg2MzY4',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Constructors',
    'name': 'Constructors',
    'color': 'd4c5f9',
    'default': False,
    'description': 'Series/DataFrame/Index/pd.array Constructors'},
   {'id': 849023693,
    'node_id': 'MDU6TGFiZWw4NDkwMjM2OTM=',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/ExtensionArray',
    'name': 'ExtensionArray',
    'color': '6138b5',
    'default': False,
    'description': 'Extending pandas with custom dtypes or arrays.'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2020-01-04T23:22:49Z',
  'updated_at': '2020-01-05T02:49:02Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/30703',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/30703',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/30703.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/30703.patch'},
  'body': "So far this just puts `take` in it, but there are a handful of other methods we'll be able to move from our existing EA Indexes."},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/30702',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/30702/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/30702/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/30702/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/30702',
  'id': 545342671,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0MzU5MjU0NDUx',
  'number': 30702,
  'title': 'DEPR: CategoricalIndex.take_nd',
  'user': {'login': 'jbrockmendel',
   'id': 8078968,
   'node_id': 'MDQ6VXNlcjgwNzg5Njg=',
   'avatar_url': 'https://avatars1.githubusercontent.com/u/8078968?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/jbrockmendel',
   'html_url': 'https://github.com/jbrockmendel',
   'followers_url': 'https://api.github.com/users/jbrockmendel/followers',
   'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}',
   'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions',
   'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs',
   'repos_url': 'https://api.github.com/users/jbrockmendel/repos',
   'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 78527356,
    'node_id': 'MDU6TGFiZWw3ODUyNzM1Ng==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Categorical',
    'name': 'Categorical',
    'color': 'e11d21',
    'default': False,
    'description': None},
   {'id': 87485152,
    'node_id': 'MDU6TGFiZWw4NzQ4NTE1Mg==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Deprecate',
    'name': 'Deprecate',
    'color': '5319e7',
    'default': False,
    'description': None}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,

In [55]:
data[2]['user']

{'login': 'AlfredoGJ',
 'id': 19152108,
 'node_id': 'MDQ6VXNlcjE5MTUyMTA4',
 'avatar_url': 'https://avatars3.githubusercontent.com/u/19152108?v=4',
 'gravatar_id': '',
 'url': 'https://api.github.com/users/AlfredoGJ',
 'html_url': 'https://github.com/AlfredoGJ',
 'followers_url': 'https://api.github.com/users/AlfredoGJ/followers',
 'following_url': 'https://api.github.com/users/AlfredoGJ/following{/other_user}',
 'gists_url': 'https://api.github.com/users/AlfredoGJ/gists{/gist_id}',
 'starred_url': 'https://api.github.com/users/AlfredoGJ/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/AlfredoGJ/subscriptions',
 'organizations_url': 'https://api.github.com/users/AlfredoGJ/orgs',
 'repos_url': 'https://api.github.com/users/AlfredoGJ/repos',
 'events_url': 'https://api.github.com/users/AlfredoGJ/events{/privacy}',
 'received_events_url': 'https://api.github.com/users/AlfredoGJ/received_events',
 'type': 'User',
 'site_admin': False}

In [56]:
retrive_data=pd.DataFrame(data,columns=['number','title','labels','state'])
retrive_data.head()

,number,title,labels,state
0,30708,CI: Test case for wrong placed space,"[{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...",open
1,30707,STY: Spaces over concat strings - batch 1,"[{'id': 106935113, 'node_id': 'MDU6TGFiZWwxMDY...",open
2,30706,CLN: replacing '.format' with f-strings in var...,"[{'id': 106935113, 'node_id': 'MDU6TGFiZWwxMDY...",open
3,30705,BUG: listlike comparisons for DTA and TDA,[],open
4,30704,REF: Share _fast_union between DTI/TDI,"[{'id': 1218227310, 'node_id': 'MDU6TGFiZWwxMj...",open

###### Interacting with Databases¶

In [59]:
import sqlite3
db=sqlite3.connect("my_database1.db")
# Drop table if it already exist using execute() method.
db.execute("drop table if exists test")
querry = """
CREATE TABLE test
(a VARCHAR(20), b VARCHAR(20),
 c REAL,        d INTEGER
);"""

con = sqlite3.connect('mydata3.sqlite')
con.execute(querry)
con.commit()

In [60]:
data = [('Atlanta', 'Georgia', 1.25, 6),
        ('Tallahassee', 'Florida', 2.6, 3),
        ('Sacramento', 'California', 1.7, 5)]
stmt = "INSERT INTO test VALUES(?, ?, ?, ?)"
con.executemany(stmt, data)
con.commit()

In [61]:
cursor = con.execute('select * from test')
rows = cursor.fetchall()
rows

[('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5)]

In [62]:
cursor.description
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

In [63]:
import sqlite3
#connecting with the database.
db = sqlite3.connect("my_database5.db")
# Drop table if it already exist using execute() method.
db.execute("drop table if exists grades1")
# Create table as per requirement
db.execute("create table grades1(id int, name text, score int)")
#inserting values inside the created table
db.execute("insert into grades1(id, name, score) values(101, 'John',99 )")
db.execute("insert into grades1(id, name, score) values(102, 'Gary',90 )")
db.execute("insert into grades1(id, name, score) values(103, 'James', 80 )")
db.execute("insert into grades1(id, name, score) values(104, 'Cathy', 85 )")
db.execute("insert into grades1(id, name, score) values(105, 'Kris',95 )")

In [64]:
db.commit()

In [65]:
results = db.execute("select * from grades1 order by id")
for row in results:
    print((row))
print("-" * 60 )

(101, 'John', 99)
(102, 'Gary', 90)
(103, 'James', 80)
(104, 'Cathy', 85)
(105, 'Kris', 95)
------------------------------------------------------------

In [66]:
results = db.execute("select * from grades1 where name = 'Gary' ")
for row in results: print(row)
print("-"* 60 )

(102, 'Gary', 90)
------------------------------------------------------------

In [67]:
results = db.execute("select * from grades1 where score >= 90 ")
for row in results:
    print(row)
print("-" * 60 )

(101, 'John', 99)
(102, 'Gary', 90)
(105, 'Kris', 95)
------------------------------------------------------------

In [68]:
results = db.execute("select name, score from grades1 order by score desc ")
for row in results:
    print(row)
print("-" * 60 )

('John', 99)
('Kris', 95)
('Gary', 90)
('Cathy', 85)
('James', 80)
------------------------------------------------------------

In [69]:
results = db.execute("select name, score from grades1 order by score")
for row in results:
    print(row)
print("-" * 60 )

('James', 80)
('Cathy', 85)
('Gary', 90)
('Kris', 95)
('John', 99)
------------------------------------------------------------